### ISSUE TITLE
Why minSdkVersion is 15?

### ISSUE THREAD

**Issue by b95505017** [grandcentrix/tray#102]
As title. Is there any API limit the `minSdkVersion`?

**Comment by StefMa** [comment]
We got that question multiple times already.
See https://github.com/grandcentrix/tray/issues/93 https://github.com/grandcentrix/tray/pull/94 and https://github.com/grandcentrix/tray/issues/58

We have no interesting to reduce it. But as you can see in the linked issues you can just override the `minSdkVersion`.

**Comment by b95505017** [comment]
Thanks for quick response!
