### ISSUE TITLE
can i use listener?

### ISSUE THREAD

**Issue by erlangp** [grandcentrix/tray#103]
can i use listener like:
`sharedPreferences.registerOnSharedPreferenceChangeListener(this)`
?
thanks

**Comment by StefMa** [comment]
Of course. Simply use it with
`trayPreference.registerOnTrayPreferencrChangeListener`. And don't forgot
about to unregister it later ☺️

Do you hä e any trouble with that? 🤔

**Comment by erlangp** [comment]
ow thank you.. its work :+1:
