### ISSUE TITLE
do I  need define different authority if using multiprocess ?

### ISSUE THREAD

**Issue by eggcaker** [grandcentrix/tray#109]
I'm using multiprocess in my app and use default provider authority. I am not sure it's the same issue as #106,  is it must be set the different authority if using multiprocess ?

**Comment by StefMa** [comment]
No. You don't have define it multiple times. Can you please share your setup and a little bit more information. Eg. which device and which os version?! 

Please do it in  #106. I'll close that for now... 

_Sent from my LGE Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
