### ISSUE TITLE
Encryption wrapper class

### ISSUE THREAD

**Issue by draekko** [grandcentrix/tray#38]
Wrote an encryption wrapper class using Tray to replace the one i had been using for SharedPreferences. Maybe someone else will find it useful. Find it here  https://github.com/draekko/securedtray

Thanks for the good work on Tray as it solved a problem i had with concurrent access to data with multiple processes & SharedPreferences. Saved me a ton of time writing a similar library from scratch.

**Comment by passsy** [comment]
Thanks for your contribution!
Personally I would have implemented a `SecureTrayPreference extends Preference<TrayItem>` like [TrayPreference](https://github.com/grandcentrix/tray/blob/master/library/src/main/java/net/grandcentrix/tray/accessor/TrayPreference.java) and pass it into a `SecureTrayModulePreferences extends TrayPreference` like [TrayModulePreferences](https://github.com/grandcentrix/tray/blob/master/library/src/main/java/net/grandcentrix/tray/TrayModulePreferences.java).
This would result into the same API as Tray but with a secure data storage.

**Comment by passsy** [comment]
Btw: using a secure Database could be another option. Just create a `ModularizedStorage` implementing a lib like https://www.zetetic.net/sqlcipher/

**Comment by draekko** [comment]
True, but i was limited in time to implement something, maybe eventually ;) Also i already had most of the code from the wrapper class for the SharedPreferences.

I already use sqlcipher in other projects, compiling it for 64 bit builds is somewhat problematic right now as they refuse to update it (there have been contributed patches for a while that they are sitting on) because they are "waiting" for openssl to update their code to compile for 64bit builds. At least that's their official response so far.  So i'd wait a while for that to happen before making anything official from that end. 

Also using sqlcipher adds a native .so library dependency (and all that brings) to a project and i didn't want that for this one i was i working on.

This was simpler. :)
