### ISSUE TITLE
not to use resValue

### ISSUE THREAD

**Issue by qwe3243002** [grandcentrix/tray#44]
Hi,
In Android Studio,we can use resValue to define authority in provider,but how to define authority in eclipse environment for multi-apps?

**Comment by passsy** [comment]
simply create a string resource

`res/xml/tray.xml`
```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="tray__authority" translatable="false">com.example.preferences</string>
</resources>
```
