### ISSUE TITLE
How to run it in specific process

### ISSUE THREAD

**Issue by xibsked** [grandcentrix/tray#52]
I am having two processes in my app. Say I have two process com.example.appname.xx and another com.example.appname.yy . By default it is running in the process com.example.appname. How can I indicate it to run this in either com.example.appname.xx orcom.example.appname.yy.Thanks.

**Comment by passsy** [comment]
override the tray from the lib in your android manifest with

```xml
        <provider
            android:name=".provider.TrayContentProvider"
            android:authorities="@string/tray__authority"
            android:exported="false"
            android:multiprocess="false"
            android:process=":someOtherProcess" />
```

**Comment by passsy** [comment]
Have you any troubles running Tray in the main app process? Could it help if Tray runs by default in its own process?

**Comment by xibsked** [comment]
No Its running fine in the main process also.
I am able to move it to the another process. Thanks passsy. You guys have really done great job!.
I was facing tonnes of problem with SharedPreferences in multi process environment . Thanks alot!
