### ISSUE TITLE
crash on android 2.3

### ISSUE THREAD

**Issue by wzystal** [grandcentrix/tray#60]
util.SqliteHelper uses a method (android.database.DatabaseUtils.queryNumEntries) which is in api level 11, leading to crash on android 2.3 device.

**Comment by passsy** [comment]
Tray doesn't support api versions lower than 15. see [`minSdkVersion 15`](https://github.com/grandcentrix/tray/blob/master/library/build.gradle#L13)

If you change the minSdkVersion you are responsible to build the support for those old versions on your own.

see #14
