### ISSUE TITLE
please reduce the minSdkVersion <=10

### ISSUE THREAD

**Issue by ynhenggg** [grandcentrix/tray#72]
Dear grandcentrix GmbH,
I like this library , it make sharedPreference so easy to use....
but it need minApi is 15 , it's wired , this limited many  customer requirements, 
because many shopping apps do not want higher api level , that means lost costom.....
so when I use it I must import the library moudle ,then set the minSdkVersion to 10 ,
but I think many developers do not know that the library's api-level could be reduced , maybe it will lost  many follows cause this...
So would please reduce it to fits much more app ?

Best Regards.

**Comment by passsy** [comment]
We think about reducing it to `11`. It's not possible to go below 11 because of some APIs which require sdkVersion `11`. 

As a workaround you can override the minSdkVersion in the AndroidManifest:

```xml
    <!-- override the min sdk version -->
    <uses-sdk tools:overrideLibrary="net.grandcentrix.tray" />
```

**Comment by ynhenggg** [comment]
Dear Pascal Welsch,
    thank you very much for your reply and your solution.....
    I will close this issues.
Best regards.
