### ISSUE TITLE
Support for Set<String>

### ISSUE THREAD

**Issue by yasinkacmaz** [grandcentrix/tray#77]
I see your library and i need to replace my shared prefs because my prefs is caching in my service and i dont want it , so Context.MODE_MULTI_PROCESS is deprecated. 

Actually i can use this library for now but i need to store Set<String> this is so important for me , can you add this support please !

- Set<String>. Is someone using this? ( Yes there is ghost developers using it :) )

**Comment by passsy** [comment]
see #7
