### ISSUE TITLE
Waiting for Maven Central

### ISSUE THREAD

**Issue by hamen** [grandcentrix/tray#8]
Hi and thanks for the cool library :+1: 
Here is Gradle support with Jitpack
https://jitpack.io/#grandcentrix/tray/v0.9

**Comment by passsy** [comment]
Pushing this lib to maven is the number one priority. We know the git clone solution isn't state of the art. 

To be honest, we haven't expected this traffic in the first week. :smile: 

ETA: this week

**Comment by passsy** [comment]
done!

Tray is now available via jcenter.

```java
dependencies {
    compile 'net.grandcentrix.tray:tray:0.9'
}
```
