### ISSUE TITLE
Is encryption planned? 

### ISSUE THREAD

**Issue by Rainer-Lang** [grandcentrix/tray#80]

**Comment by passsy** [comment]
No, but the API allows you to implement a `TrayStorage` which supports encryption. With a little effort you should be able to integrate sqlcipher and use most of the [`ContentProviderStorage`](https://github.com/grandcentrix/tray/blob/master/library/src/main/java/net/grandcentrix/tray/provider/ContentProviderStorage.java) code.

```java
public class SecureTrayPreferences extends AbstractTrayPreference<SecureContentProviderStorage> {

    public TrayPreferences(@NonNull final Context context, @NonNull final String module,
            final int version, final TrayStorage.Type type) {
        super(new SecureContentProviderStorage(context, module, type), version);
    }
}
```
