### ISSUE TITLE
二个app都用tray,安装在同一个手机上面会有bug问题

### ISSUE THREAD

**Issue by douya40** [grandcentrix/tray#85]
会不能同时安装

**Comment by jreehuis** [comment]
Please report issues in English. So everyone can follow the conversation and could participate.

**Comment by douya40** [comment]
ok,Two app with tray for caching, cannot be installed on the same cell phone at the same time.

**Comment by StefMa** [comment]
Is this a joke? @douya40 
You have already asked this question three days ago (#83).

**Comment by douya40** [comment]
no,This is a fact

**Comment by StefMa** [comment]
And @passsy [answered](https://github.com/grandcentrix/tray/issues/83#issuecomment-254478251).
Don't help this information?

**Comment by douya40** [comment]
I use the Android studio. Two module using tray was not installed on my cell phone at the same time, an error is as follows. Remove the tray was normal, erro:Installation failed with message INSTALL_FAILED_CONFLICTING_PROVIDER.
It is possible that this issue is resolved by uninstalling an existing version of the apk if it is present, and then re-installing.

WARNING: Uninstalling will remove the application data!

Do you want to uninstall the existing application?

**Comment by ysyyork** [comment]
@douya40 dude this is not related to tray, look at the answer in another thread. it's your package name
