### ISSUE TITLE
Can't initialise new AppPreferences(getContext())

### ISSUE THREAD

**Issue by dfloureiro** [grandcentrix/tray#90]
Hi everyone, here asking for some help!

It crashed in the TrayContract.java

I get a nullpointerexpection, in this method
@NonNull
    private static String getAuthority(@NonNull final Context context) {
        return TextUtils.isEmpty(sTestAuthority) ?
                context.getString(R.string.tray__authority) :
                sTestAuthority;
    }

I believe it can't get the context.getString(R.string.tray__authority) in here.

- I set the the tray__authority and I cleaned the project.
- I set one different value for every flavour, based on the the ApplicationId.
- if I do context.getString(R.string.tray__authority) I get the right value.
- It's the same context has the one I gave to your AppPreferences.

I don't understand the issue, can somebody help?

**Comment by StefMa** [comment]
When you get a NullPointer that it seems that your context you put in is
null. Have you checked if that is really non null?

**Comment by dfloureiro** [comment]
I'ts not null :(

**Comment by StefMa** [comment]
Can you post some code how do you use initialize tray and how your
build.gradle looks...

**Comment by dfloureiro** [comment]
I detected the problem!

ContentProviderStorage.java
    public ContentProviderStorage(@NonNull final Context context, @NonNull final String module,
            @NonNull final Type type) {
        super(module, type);
        mContext = context.getApplicationContext();
        mTrayUri = new TrayUri(mContext);
        mProviderHelper = new TrayProviderHelper(mContext);
    }

mContext is null! why aren't you using the context I gave you instead?
My ApplicationContext() at this point is, in fact, null!

**Comment by jannisveerkamp** [comment]
Maybe we should check if the Application Context is available and otherwise use the context itself.

This can happen in Tests.

**Comment by StefMa** [comment]
I can't be happen that the app context is null but an activity context (for
example) is not null.

Anyway. On which platform are you seeing this issue? As far as I can
remember that I saw that in specific platforms getApplicationContext can
return null... But don't remember exactly...

**Comment by dfloureiro** [comment]
The context I used is the getBaseContext() from a class that extends android.app.Application
Does this answer your question?

**Comment by dfloureiro** [comment]
basically you should not assume you can call getApplicationContext() from any context.
If I give you a context on attachBaseContext() from an android.app.Application, the this.getApplicationContext() will return null!
I think what @jannisveerkamp suggested is a nice solution for this.

**Comment by StefMa** [comment]
Probably yes, this answer my question 😀
I really didn't know what getBaseContext returns. But as far as I know this
can be the wrong (or null) context...

So probably you have to change the context which you put in into the
AppPreferences...

Why not just using this, when you init Tray in your Application?

**Comment by dfloureiro** [comment]
I want to use tray to load some remote "app settings" that need to be loaded on the very launch (like theme and stuff like that).
My idea is to have an alarmmanager that will start a service on background, to update this remote settings, save them using tray, that will load once the app is opened. As you know, without tray or a content provider, the app will not load the latest shared preferences (that was what I was using previously).
The problem is, at this very start, this is the only context I have.
I'm afraid that if I delay this process because of the context, some of this settings will not be applied at the very start. But I'll try to improvise a solution 😄

Anyway, I think it would be cool if you could do this improvement/fix in a next release 😄 

Thank you for your help!

**Comment by dfloureiro** [comment]
I've manage to solve the issue on my code already by changing the given context 😃 
Please consider this modification in the future. Thank you for your time!
