### ISSUE TITLE
why the minSdkVersion is 15 not 14？

### ISSUE THREAD

**Issue by bacy** [grandcentrix/tray#93]

**Comment by passsy** [comment]
No specific reason. But there are no phones out there which didn't got an update for API 15. We are open for your PR

As a workaround you can override the minSdkVersion in the AndroidManifest:

``` xml
    <!-- override the min sdk version -->
    <uses-sdk tools:overrideLibrary="net.grandcentrix.tray" />
```

**Comment by bacy** [comment]
3q, i will have a try
