### ISSUE TITLE
java.lang.ClassNotFoundException: Didn't find class "net.grandcentrix.tray.provider.TrayContentProvider" on path: DexPathList

### ISSUE THREAD

**Issue by douya40** [grandcentrix/tray#98]
java.lang.ClassNotFoundException: Didn't find class "net.grandcentrix.tray.provider.TrayContentProvider" on path: DexPathList

**Comment by passsy** [comment]
Are you using proguard? Have you enabled multidex?

**Comment by WangLaoSeng** [comment]
i have met this problem too

 it's because multidex ,make sure that you app's multidex  is compatible android under 5.0

**Comment by erlangp** [comment]
i add `multiDexEnabled false` at build.gradle file, then no error 😄
